favicon: null
name: GT Tester
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.4874552
  lightness: 1
  brandColors:
    - '#FFFEF0'
    - '#006FBD'
    - '#000000'
    - '#004A7E'
    - '#78AECE'
  rhythmicContrast: 0.5
typography_spectrum: 0.27665
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.03384
analytics:
  twitter: null
  google: null
  facebook: null
