name: GT Tester
favicon: null
layout_spectrum: 0.03384
typography_spectrum: 0.27665
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: IT Support - Website Design - Remote Monitoring - Datto Server Backups
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFEF0'
    - '#006FBD'
    - '#000000'
    - '#004A7E'
    - '#78AECE'
  brandStrength: 0.4874552
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
