layout_spectrum: 1
typography_spectrum: 0.2453626
color:
  saturation: 0.7816189
  lightness: 0.2504216
  brandStrength: 0.007405776
  brandColors:
    - '#CFDFF2'
    - '#1E1F20'
    - '#808A90'
    - '#424341'
    - '#5D6366'
  rhythmicContrast: 0.7428331
name: GT Tester
