collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2892074
  lightness: 0.6922429
  brandStrength: 0.8086004
  brandColors:
    - '#FFFEF0'
    - '#006FBD'
    - '#000000'
    - '#004A7E'
    - '#78AECE'
  rhythmicContrast: 0.5438449
typography_spectrum: 0.3010118
layout_spectrum: 0
name: GT Tester
