title: GRISSOM TECHNOLOGY
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.06063433
  lightness: 0.9375
  brandColors:
    - '#FFFEF0'
    - '#006FBD'
    - '#000000'
    - '#004A7E'
    - '#78AECE'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: GT Tester
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.508862
layout_spectrum: 0.07695895
